// Seed data to initialize the blog manager if no data exists in LocalStorage
const SEED_POSTS = [
  {
    id: "seed-1",
    title: "AI Agents Are Changing How We Write Software — And Most Developers Aren't Ready",
    slug: "ai-agents-are-changing-how-we-write-software",
    date: "2026-02-10",
    readTime: 4,
    pinned: true,
    tags: ["AI", "SOFTWARE ENGINEERING", "DEVELOPER TOOLS"],
    desc: "AI agents don't just autocomplete your code anymore. They plan, execute, debug, and ship. Here's what that actually means for developer workflows.",
    image: "/blogs/keyboard_setup.png",
    content: `<h1>Introduction</h1><p>AI coding tools are evolving at breakneck speed. We've graduated from basic line completion to autonomous agents that can read an entire repository, outline a multi-file plan, execute edits, run unit tests, and resolve compilation errors.</p><p>But as these agents become more active in our codebases, they are fundamentally altering what it means to be a software engineer.</p><h1>From Coders to Systems Architects</h1><p>When an AI agent can write 500 lines of clean boilerplate code in 10 seconds, the value of manual code typing drops to near zero. Instead, the developer's role shifts to system architect and code reviewer.</p><p>You are no longer just writing instructions; you are directing an autonomous assistant, defining system design constraints, validating security requirements, and reviewing complex PR diffs.</p><h1>The Agentic Workflow</h1><p>An agentic coding workflow usually looks like this:</p><ol><li><strong>Prompt &amp; Goal</strong>: Define the user story or bug description clearly.</li><li><strong>Planning Phase</strong>: The agent outlines which files to modify and how.</li><li><strong>Execution Phase</strong>: The agent applies edits and compiles the code.</li><li><strong>Validation Phase</strong>: The agent executes test suites and iterates on failures.</li><li><strong>Review</strong>: The human developer inspects the resulting pull request.</li></ol><p>This iterative loop can compress a task that once took two days into a 15-minute verification session.</p><h1>The Skills You Need Now</h1><p>To thrive in the era of agentic software development, focus on:</p><ul><li><strong>System Design &amp; API Contracts</strong>: Defining clean boundaries makes it much easier for agents to integrate code.</li><li><strong>Advanced Debugging</strong>: You will spend less time coding and more time figuring out why an agent's code failed under specific edge cases.</li><li><strong>PR Reviewing</strong>: Developing an eye for subtle logical bugs or security vulnerabilities introduced by generated code.</li></ul>`,
    created_at: "2026-02-10T12:00:00.000Z",
    updated_at: "2026-02-10T12:00:00.000Z"
  },
  {
    id: "seed-2",
    title: "Almost Half of AI-Written Code Fails in Production — Here's Why That Matters",
    slug: "almost-half-of-ai-written-code-fails",
    date: "2026-04-17",
    readTime: 6,
    pinned: true,
    tags: ["AI", "SOFTWARE ENGINEERING"],
    desc: "A new report found that 44% of AI-generated code breaks when it hits real users. Not in testing. In production. Here's what's actually going on.",
    image: "/blogs/ai_code_fails.png",
    content: `<h1>Introduction</h1><p>A report dropped this week that most developers scrolled past.</p><p>Lightrun surveyed 200 senior engineering leaders across the US, UK, and EU. The finding that stood out: <strong>44% of AI-generated code changes still fail</strong> when they reach real users in production.</p><p>Not in your local environment. Not in staging. In production, with real users.</p><h1>Why Tests Don't Catch AI Bugs</h1><p>The gap between local testing and production reality is growing wider. While AI is great at generating unit tests for the code it just wrote, those tests often suffer from the same logical blindspots as the code itself.</p><p>Here is a typical pattern of a failing stream parser generated by LLMs:</p><pre class="ql-syntax" spellcheck="false">import system_status
from core import dataloader

def process_stream():
    # Load initial data from core
    data = dataloader.fetch_batch()
    if system_status.is_healthy():
        try:
            results = validate_data(data)
            # data_logger.event("Success")
        except ProcessingError as e:
            handle_error(e)
            return None
    return None</pre><p>In this code, notice how the exception handling is completely silent on validation failures and returns <code>None</code> without notifying the upstream buffer. In production, under high concurrency, this leads to silent buffer exhaustion.</p><h1>The False Sense of Velocity</h1><p>Managers look at "lines of code written" or "tickets closed" and see a 40% increase in developer velocity. But they ignore the downstream cost of troubleshooting, rollbacks, and hotfixes.</p><p>Engineering velocity isn't how fast you can write code. It's how fast you can deliver <em>working</em> software that stays working.</p><h1>How to Mitigate AI Failures</h1><p>If you are using AI tools in your codebase, you need to adjust your workflow:</p><ol><li><strong>Stricter PR Reviews</strong>: Treat AI-generated pull requests with double the scrutiny of a junior developer's PR.</li><li><strong>Defensive Coding Patterns</strong>: Never assume the happy path. Always validate inputs and handle edge cases explicitly.</li><li><strong>Better Observability</strong>: Ensure you have robust tracing and logging to catch issues in staging before they migrate to production.</li></ol>`,
    created_at: "2026-04-17T14:30:00.000Z",
    updated_at: "2026-04-17T14:30:00.000Z"
  },
  {
    id: "seed-3",
    title: "Your Tools Are Getting More Expensive — And It's Only Going to Get Worse",
    slug: "your-tools-are-getting-more-expensive",
    date: "2026-05-01",
    readTime: 6,
    pinned: false,
    tags: ["DEVELOPER TOOLS", "AI"],
    desc: "GitHub Copilot paused signups, removed models, and is switching to token billing. Amazon Bedrock keeps locking models. Here is how to keep costs manageable.",
    image: "/blogs/ai_tools_cost.png",
    content: `<h1>Introduction</h1><p>If you feel like your monthly SaaS bill for development tools is rising, you aren't imagining things. The compute costs associated with running massive LLM foundation models are starting to catch up with developer tool companies, and they are passing those costs directly down to engineering teams.</p><p>From seat-based pricing to token consumption limits, the developer tools landscape is shifting.</p><h1>The Real Cost of LLMs</h1><p>Running a modern LLM cluster is incredibly expensive. Training a frontier model costs tens of millions of dollars in compute time, and serving API queries requires active GPU farms.</p><p>For years, developer tools heavily subsidized these costs to drive adoption. But as usage grows from simple autocompletes to agents running thousands of queries, subsidies are drying up. We are starting to see:</p><ul><li><strong>Token Billing</strong>: Transitioning from a flat monthly fee to paying per input/output token.</li><li><strong>Rate Limits</strong>: Strict caps on how many agent steps or generation runs you can perform each day.</li><li><strong>Model Tiers</strong>: Locking premium models behind more expensive enterprise packages.</li></ul><h1>Strategies to Optimize Costs</h1><p>As developers, we need to adapt to these changes by optimization:</p><ol><li><strong>Context Minimization</strong>: Stop sending your entire codebase in the context window. Use vector search (RAG) to only send relevant snippets.</li><li><strong>Local Models</strong>: Use lightweight local LLMs (like Llama 3 or Mistral) running on your local GPU for simple code completion and boilerplate generation.</li><li><strong>Caching</strong>: Utilize prompt caching to avoid paying for the same system prompts and repository structures repeatedly.</li><li><strong>Hybrid Workflows</strong>: Save expensive frontier models for complex architectural decisions and debugging sessions.</li></ol>`,
    created_at: "2026-05-01T09:15:00.000Z",
    updated_at: "2026-05-01T09:15:00.000Z"
  }
];

// Initialize application state
let posts = [];
let currentPostId = null;
let activeTags = [];
let isSlugAuto = true;
let quill = null;

// Initialize elements
const titleInput = document.getElementById("post-title");
const slugInput = document.getElementById("slug-input");
const slugPreview = document.getElementById("slug-preview");
const btnEditSlug = document.getElementById("btn-edit-slug");
const slugLockIcon = document.getElementById("slug-lock-icon");
const slugLockText = document.getElementById("slug-lock-text");

const descTextarea = document.getElementById("post-desc");
const dateInput = document.getElementById("post-date");
const readTimeInput = document.getElementById("post-read-time");
const readTimeIndicator = document.getElementById("read-time-indicator");
const pinnedCheckbox = document.getElementById("post-pinned");
const imageInput = document.getElementById("post-image");
const imagePreview = document.getElementById("image-preview");
const imagePlaceholder = document.getElementById("image-placeholder");

const tagInput = document.getElementById("tag-input");
const tagsWrapper = document.getElementById("tags-wrapper");

const btnSave = document.getElementById("btn-save");
const btnReset = document.getElementById("btn-reset");
const btnDelete = document.getElementById("btn-delete-current");
const btnNewPost = document.getElementById("btn-new-post");
const postsListContainer = document.getElementById("posts-list");
const searchInput = document.getElementById("search-posts");

// Export/Import/Modal elements
const btnExportSql = document.getElementById("btn-export-sql");
const btnExportJson = document.getElementById("btn-export-json");
const btnImportJsonTrigger = document.getElementById("btn-import-json-trigger");
const importJsonFile = document.getElementById("import-json-file");
const sqlModal = document.getElementById("sql-modal");
const btnCloseModal = document.getElementById("btn-close-modal");
const sqlCodeContainer = document.getElementById("sql-code-container");
const btnCopySql = document.getElementById("btn-copy-sql");
const btnDownloadSql = document.getElementById("btn-download-sql");

// Initialize application
window.addEventListener("DOMContentLoaded", () => {
  initQuill();
  loadData();
  setupEventListeners();
  resetEditor();
  renderPostsList();
  lucide.createIcons();
});

// Setup Quill rich text editor
function initQuill() {
  quill = new Quill("#editor", {
    theme: "snow",
    placeholder: "Tell your story... Use headers, bold text, blocks of code, and bullet lists.",
    modules: {
      toolbar: [
        [{ 'header': [1, 2, false] }],
        ['bold', 'italic', 'underline', 'strike'],
        ['blockquote', 'code-block'],
        [{ 'list': 'ordered'}, { 'list': 'bullet' }],
        ['link', 'image'],
        ['clean']
      ]
    }
  });

  // Calculate read time on editor text change
  quill.on("text-change", () => {
    const text = quill.getText();
    const wordCount = text.trim().split(/\s+/).filter(w => w.length > 0).length;
    const autoMinutes = Math.max(1, Math.ceil(wordCount / 200));
    
    readTimeIndicator.textContent = `Auto-calculated: ${autoMinutes} min`;
    
    // Only autofill input if it is empty or user hasn't typed in it
    if (!readTimeInput.value || readTimeInput.dataset.overridden === "false") {
      readTimeInput.value = autoMinutes;
      readTimeInput.dataset.overridden = "false";
    }
  });
}

// Setup Event Listeners
function setupEventListeners() {
  // Save post
  btnSave.addEventListener("click", savePost);

  // Reset editor
  btnReset.addEventListener("click", () => {
    if (confirm("Are you sure you want to clear current edits?")) {
      resetEditor();
    }
  });

  // New post trigger
  btnNewPost.addEventListener("click", () => {
    currentPostId = null;
    resetEditor();
    renderPostsList();
  });

  // Delete post
  btnDelete.addEventListener("click", deletePost);

  // Search posts
  searchInput.addEventListener("input", renderPostsList);

  // Title automatic slug generator
  titleInput.addEventListener("input", (e) => {
    if (isSlugAuto) {
      const slugVal = generateSlug(e.target.value);
      slugPreview.textContent = slugVal || "my-post-slug";
      slugInput.value = slugVal;
    }
  });

  // Manual slug edit toggle
  btnEditSlug.addEventListener("click", () => {
    if (isSlugAuto) {
      // Toggle to manual
      isSlugAuto = false;
      slugPreview.classList.add("hidden");
      slugInput.classList.remove("hidden");
      slugInput.value = slugPreview.textContent === "my-post-slug" ? "" : slugPreview.textContent;
      slugInput.focus();
      slugLockText.textContent = "Custom";
      slugLockIcon.setAttribute("data-lucide", "unlock");
    } else {
      // Toggle back to auto
      isSlugAuto = true;
      slugPreview.classList.remove("hidden");
      slugInput.classList.add("hidden");
      const slugVal = generateSlug(titleInput.value);
      slugPreview.textContent = slugVal || "my-post-slug";
      slugInput.value = slugVal;
      slugLockText.textContent = "Auto";
      slugLockIcon.setAttribute("data-lucide", "lock");
    }
    lucide.createIcons();
  });

  slugInput.addEventListener("input", (e) => {
    const slugVal = generateSlug(e.target.value);
    slugInput.value = slugVal;
    slugPreview.textContent = slugVal || "my-post-slug";
  });

  // Read Time manual override tracker
  readTimeInput.addEventListener("input", () => {
    readTimeInput.dataset.overridden = "true";
    if (!readTimeInput.value) {
      readTimeInput.dataset.overridden = "false";
    }
  });

  // Image URL input changes -> update preview
  imageInput.addEventListener("input", (e) => {
    updateImagePreview(e.target.value);
  });

  // Tags input keys
  tagInput.addEventListener("keydown", (e) => {
    if (e.key === "Enter" || e.key === ",") {
      e.preventDefault();
      const val = tagInput.value.trim().toUpperCase();
      if (val && !activeTags.includes(val)) {
        activeTags.push(val);
        renderTags();
      }
      tagInput.value = "";
    }
  });

  // SQL Modal actions
  btnExportSql.addEventListener("click", openSqlModal);
  btnCloseModal.addEventListener("click", () => sqlModal.classList.add("hidden"));
  btnCopySql.addEventListener("click", copySqlToClipboard);
  btnDownloadSql.addEventListener("click", downloadSqlFile);

  // JSON backup exports
  btnExportJson.addEventListener("click", exportJSONBackup);

  // JSON import triggers
  btnImportJsonTrigger.addEventListener("click", () => importJsonFile.click());
  importJsonFile.addEventListener("change", importJSONBackup);

  // Close modal when clicking background
  window.addEventListener("click", (e) => {
    if (e.target === sqlModal) {
      sqlModal.classList.add("hidden");
    }
  });
}

// Generate a URL friendly slug
function generateSlug(text) {
  return text
    .toString()
    .toLowerCase()
    .normalize('NFD') // split accented characters into their base letters and diacritical marks
    .replace(/[\u0300-\u036f]/g, '') // remove diacritical marks
    .replace(/\s+/g, '-') // replace spaces with hyphens
    .replace(/[^\w\-]+/g, '') // remove non-word chars (except hyphens)
    .replace(/\-\-+/g, '-') // replace multiple hyphens with single hyphen
    .replace(/^-+/, '') // trim leading hyphens
    .replace(/-+$/, ''); // trim trailing hyphens
}

// Load data from LocalStorage
function loadData() {
  const localData = localStorage.getItem("antigravity_blogs");
  if (localData) {
    posts = JSON.parse(localData);
  } else {
    // Load default seed data
    posts = [...SEED_POSTS];
    saveToLocalStorage();
  }
}

// Save database to LocalStorage
function saveToLocalStorage() {
  localStorage.setItem("antigravity_blogs", JSON.stringify(posts));
}

// Reset Editor fields
function resetEditor() {
  titleInput.value = "";
  slugInput.value = "";
  slugPreview.textContent = "my-post-slug";
  isSlugAuto = true;
  slugPreview.classList.remove("hidden");
  slugInput.classList.add("hidden");
  slugLockText.textContent = "Auto";
  slugLockIcon.setAttribute("data-lucide", "lock");

  descTextarea.value = "";
  
  // Set date to today
  const today = new Date().toISOString().split("T")[0];
  dateInput.value = today;
  
  readTimeInput.value = "";
  readTimeInput.dataset.overridden = "false";
  readTimeIndicator.textContent = "Auto-calculating...";
  
  pinnedCheckbox.checked = false;
  imageInput.value = "";
  updateImagePreview("");
  
  activeTags = [];
  renderTags();
  
  if (quill) {
    quill.setContents([]);
  }

  btnDelete.classList.add("hidden");
  
  // Remove highlighted selection in sidebar
  const cards = document.querySelectorAll(".post-card");
  cards.forEach(card => card.classList.remove("post-card-active"));
  
  lucide.createIcons();
}

// Load a specific post into the editor
function loadPost(postId) {
  const post = posts.find(p => p.id === postId);
  if (!post) return;

  currentPostId = post.id;
  
  titleInput.value = post.title;
  slugInput.value = post.slug;
  slugPreview.textContent = post.slug;
  
  // Set custom slug state
  isSlugAuto = false;
  slugPreview.classList.add("hidden");
  slugInput.classList.remove("hidden");
  slugLockText.textContent = "Custom";
  slugLockIcon.setAttribute("data-lucide", "unlock");

  descTextarea.value = post.desc || "";
  dateInput.value = post.date;
  readTimeInput.value = post.readTime;
  readTimeInput.dataset.overridden = "true";
  
  pinnedCheckbox.checked = !!post.pinned;
  imageInput.value = post.image || "";
  updateImagePreview(post.image || "");
  
  activeTags = [...(post.tags || [])];
  renderTags();
  
  if (quill) {
    quill.root.innerHTML = post.content || "";
  }

  btnDelete.classList.remove("hidden");
  
  // Highlight card in sidebar
  const cards = document.querySelectorAll(".post-card");
  cards.forEach(card => {
    if (card.dataset.id === postId) {
      card.classList.add("post-card-active");
    } else {
      card.classList.remove("post-card-active");
    }
  });

  lucide.createIcons();
}

// Save post to database
function savePost() {
  const title = titleInput.value.trim();
  const desc = descTextarea.value.trim();
  const date = dateInput.value;
  const content = quill.root.innerHTML.trim();
  const rawText = quill.getText().trim();

  // Basic validations
  if (!title) {
    showToast("Please enter a title.", "warning");
    titleInput.focus();
    return;
  }
  if (!desc) {
    showToast("Please enter a short summary description.", "warning");
    descTextarea.focus();
    return;
  }
  if (rawText.length === 0) {
    showToast("Please write some content in the blog body.", "warning");
    return;
  }

  // Double check slug uniqueness
  const slug = slugInput.value.trim() || generateSlug(title);
  const duplicate = posts.find(p => p.slug === slug && p.id !== currentPostId);
  if (duplicate) {
    showToast(`The slug "${slug}" is already in use by another post!`, "warning");
    slugInput.focus();
    return;
  }

  const readTime = parseInt(readTimeInput.value) || 1;
  const pinned = pinnedCheckbox.checked;
  const image = imageInput.value.trim();

  const nowISO = new Date().toISOString();

  if (currentPostId) {
    // Update existing post
    const index = posts.findIndex(p => p.id === currentPostId);
    if (index !== -1) {
      posts[index] = {
        ...posts[index],
        title,
        slug,
        desc,
        content,
        date,
        readTime,
        pinned,
        image,
        tags: [...activeTags],
        updated_at: nowISO
      };
      showToast("Post updated successfully!");
    }
  } else {
    // Create new post
    const newPost = {
      id: "post-" + Date.now(),
      title,
      slug,
      desc,
      content,
      date,
      readTime,
      pinned,
      image,
      tags: [...activeTags],
      created_at: nowISO,
      updated_at: nowISO
    };
    posts.unshift(newPost); // Add to beginning
    currentPostId = newPost.id;
    btnDelete.classList.remove("hidden");
    showToast("Post created successfully!");
  }

  saveToLocalStorage();
  renderPostsList();
  
  // Make sure current card is highlighted
  const cards = document.querySelectorAll(".post-card");
  cards.forEach(card => {
    if (card.dataset.id === currentPostId) {
      card.classList.add("post-card-active");
    } else {
      card.classList.remove("post-card-active");
    }
  });
}

// Delete post
function deletePost() {
  if (!currentPostId) return;
  
  if (confirm("Are you sure you want to permanently delete this post? This action cannot be undone.")) {
    posts = posts.filter(p => p.id !== currentPostId);
    saveToLocalStorage();
    showToast("Post deleted successfully!", "success");
    currentPostId = null;
    resetEditor();
    renderPostsList();
  }
}

// Render active tags badges
function renderTags() {
  // Remove previous badges, leaving the input
  const badges = tagsWrapper.querySelectorAll(".tag-badge");
  badges.forEach(b => b.remove());

  activeTags.forEach((tag, idx) => {
    const badge = document.createElement("span");
    badge.className = "tag-badge text-[10px] font-mono font-bold py-1 px-2.5 rounded flex items-center gap-1.5";
    badge.innerHTML = `
      ${tag}
      <button class="hover:text-white transition" onclick="removeTag(${idx})">
        <i data-lucide="x" class="w-3 h-3"></i>
      </button>
    `;
    tagsWrapper.insertBefore(badge, tagInput);
  });
  
  lucide.createIcons();
}

// Remove tag helper
window.removeTag = function(index) {
  activeTags.splice(index, 1);
  renderTags();
};

// Update Featured Image preview container
function updateImagePreview(url) {
  if (url) {
    imagePreview.src = url;
    imagePreview.classList.remove("hidden");
    imagePlaceholder.classList.add("hidden");
    
    // Add image error handler
    imagePreview.onerror = () => {
      imagePreview.classList.add("hidden");
      imagePlaceholder.classList.remove("hidden");
      imagePlaceholder.innerHTML = `
        <i data-lucide="image-off" class="w-6 h-6 text-red-400"></i>
        <span class="text-red-400">Failed to load preview image</span>
      `;
      lucide.createIcons();
    };
  } else {
    imagePreview.classList.add("hidden");
    imagePlaceholder.classList.remove("hidden");
    imagePlaceholder.innerHTML = `
      <i data-lucide="image" class="w-6 h-6 stroke-[1.5]"></i>
      <span>Live Image Preview</span>
    `;
    lucide.createIcons();
  }
}

// Render the sidebar list of posts
function renderPostsList() {
  const query = searchInput.value.toLowerCase().trim();
  postsListContainer.innerHTML = "";

  const filteredPosts = posts.filter(p => 
    p.title.toLowerCase().includes(query) || 
    p.desc.toLowerCase().includes(query) ||
    p.tags.some(tag => tag.toLowerCase().includes(query))
  );

  if (filteredPosts.length === 0) {
    postsListContainer.innerHTML = `
      <div class="text-center py-8 text-muted-foreground text-xs border border-dashed border-border rounded-xl">
        No matches found.
      </div>
    `;
    return;
  }

  filteredPosts.forEach(post => {
    const card = document.createElement("div");
    card.className = `post-card panel p-4 cursor-pointer flex flex-col gap-2 hover:bg-panel-2/50 transition duration-300 relative ${post.id === currentPostId ? 'post-card-active' : ''}`;
    card.dataset.id = post.id;
    
    // Build tags badges
    const tagsBadges = post.tags.slice(0, 3).map(tag => 
      `<span class="text-[9px] font-bold px-1.5 py-0.5 rounded bg-muted/60 text-muted-foreground">${tag}</span>`
    ).join(" ");

    card.innerHTML = `
      <div class="flex justify-between items-start gap-2">
        <h3 class="text-xs font-bold text-foreground line-clamp-2 font-display hover:text-accent transition">${post.title}</h3>
        ${post.pinned ? `<i data-lucide="pin" class="w-3.5 h-3.5 text-accent flex-shrink-0" title="Pinned to Featured"></i>` : ''}
      </div>
      <p class="text-[10px] text-muted-foreground line-clamp-2">${post.desc || ''}</p>
      <div class="flex items-center justify-between mt-1 text-[9px] font-mono text-muted-foreground">
        <span>${formatDateDisplay(post.date)}</span>
        <span>${post.readTime} min read</span>
      </div>
      <div class="flex flex-wrap gap-1 mt-1">
        ${tagsBadges}
      </div>
    `;

    card.addEventListener("click", () => loadPost(post.id));
    postsListContainer.appendChild(card);
  });

  lucide.createIcons();
}

// Convert YYYY-MM-DD to "MMM DD, YYYY" (e.g. Feb 10, 2026) for display
function formatDateDisplay(dateStr) {
  if (!dateStr) return "";
  const parts = dateStr.split("-");
  if (parts.length !== 3) return dateStr;
  
  const dateObj = new Date(parts[0], parts[1] - 1, parts[2]);
  return dateObj.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
}

// Toast Notifications
function showToast(message, type = "success") {
  const toast = document.getElementById("toast");
  const toastMsg = document.getElementById("toast-message");
  
  toastMsg.textContent = message;
  
  // Set styles based on toast type
  if (type === "success") {
    toast.className = "fixed bottom-6 right-6 z-50 py-3 px-5 bg-emerald-500/10 border border-emerald-500 text-emerald-400 rounded-xl text-xs font-semibold flex items-center gap-2 shadow-xl shadow-emerald-500/10 transition-all duration-300 transform translate-y-0 opacity-100";
    toast.querySelector("i").setAttribute("data-lucide", "check-circle");
  } else {
    toast.className = "fixed bottom-6 right-6 z-50 py-3 px-5 bg-amber-500/10 border border-amber-500 text-amber-400 rounded-xl text-xs font-semibold flex items-center gap-2 shadow-xl shadow-amber-500/10 transition-all duration-300 transform translate-y-0 opacity-100";
    toast.querySelector("i").setAttribute("data-lucide", "alert-circle");
  }

  lucide.createIcons();

  // Hide after 3 seconds
  setTimeout(() => {
    toast.className = "fixed bottom-6 right-6 z-50 py-3 px-5 bg-accent-2/15 border border-accent-2 text-accent-2 rounded-xl text-xs font-semibold flex items-center gap-2 shadow-xl shadow-accent-2/10 transition-all duration-300 transform translate-y-12 opacity-0 pointer-events-none";
  }, 3000);
}

// Generate SQLAlchemy SQL inserts
function generateSQLScript() {
  let sql = `-- SQLAlchemy Blog Seed Data Script\n`;
  sql += `-- Auto-generated by Antigravity Blog Studio\n`;
  sql += `-- Compatible with SQLAlchemy Post & Tag Models\n\n`;

  // Get active tags from all posts to seed tags table
  const allTags = new Set();
  posts.forEach(post => {
    post.tags.forEach(tag => allTags.add(tag.toUpperCase().replace(/'/g, "''")));
  });

  sql += `-- Seed tags table\n`;
  allTags.forEach(tag => {
    sql += `INSERT INTO tags (name) VALUES ('${tag}') ON CONFLICT(name) DO NOTHING;\n`;
  });
  sql += `\n`;

  sql += `-- Seed posts and post-tag relations\n`;
  posts.forEach(post => {
    const escapedSlug = post.slug.replace(/'/g, "''");
    const escapedTitle = post.title.replace(/'/g, "''");
    const escapedDesc = post.desc.replace(/'/g, "''");
    
    // Quill saves formatted html body content
    const escapedContent = post.content.replace(/'/g, "''");
    const escapedImage = (post.image || "").replace(/'/g, "''");
    const publishedDate = post.date; // YYYY-MM-DD
    const isPinned = post.pinned ? 1 : 0;
    
    sql += `-- Seed Post: "${escapedTitle}"\n`;
    sql += `INSERT INTO posts (slug, title, desc, content, published_date, read_time_minutes, pinned, image, created_at, updated_at)\n`;
    sql += `VALUES (\n`;
    sql += `  '${escapedSlug}',\n`;
    sql += `  '${escapedTitle}',\n`;
    sql += `  '${escapedDesc}',\n`;
    sql += `  '${escapedContent}',\n`;
    sql += `  '${publishedDate}',\n`;
    sql += `  ${post.readTime},\n`;
    sql += `  ${isPinned},\n`;
    sql += `  ${escapedImage ? `'${escapedImage}'` : 'NULL'},\n`;
    sql += `  CURRENT_TIMESTAMP,\n`;
    sql += `  CURRENT_TIMESTAMP\n`;
    sql += `) ON CONFLICT(slug) DO UPDATE SET\n`;
    sql += `  title = excluded.title,\n`;
    sql += `  desc = excluded.desc,\n`;
    sql += `  content = excluded.content,\n`;
    sql += `  published_date = excluded.published_date,\n`;
    sql += `  read_time_minutes = excluded.read_time_minutes,\n`;
    sql += `  pinned = excluded.pinned,\n`;
    sql += `  image = excluded.image,\n`;
    sql += `  updated_at = CURRENT_TIMESTAMP;\n\n`;

    // Map tags
    post.tags.forEach(tag => {
      const escapedTag = tag.toUpperCase().replace(/'/g, "''");
      sql += `-- Map Tag "${escapedTag}" to "${escapedTitle}"\n`;
      sql += `INSERT INTO post_tag (post_id, tag_id)\n`;
      sql += `VALUES (\n`;
      sql += `  (SELECT id FROM posts WHERE slug = '${escapedSlug}'),\n`;
      sql += `  (SELECT id FROM tags WHERE name = '${escapedTag}')\n`;
      sql += `) ON CONFLICT DO NOTHING;\n\n`;
    });
  });

  return sql;
}

// Open SQL Modal
function openSqlModal() {
  if (posts.length === 0) {
    showToast("No posts available to export.", "warning");
    return;
  }
  const sqlContent = generateSQLScript();
  sqlCodeContainer.textContent = sqlContent;
  sqlModal.classList.remove("hidden");
}

// Copy SQL to Clipboard
function copySqlToClipboard() {
  const sqlText = sqlCodeContainer.textContent;
  navigator.clipboard.writeText(sqlText)
    .then(() => showToast("SQL Script copied to clipboard!"))
    .catch(() => showToast("Failed to copy text.", "warning"));
}

// Download SQL Script as File
function downloadSqlFile() {
  const sqlText = sqlCodeContainer.textContent;
  const blob = new Blob([sqlText], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "seed_portfolio_blogs.sql";
  a.click();
  URL.revokeObjectURL(url);
  showToast("SQL file downloaded successfully!");
}

// Export database as JSON file
function exportJSONBackup() {
  if (posts.length === 0) {
    showToast("No posts available to backup.", "warning");
    return;
  }
  const jsonStr = JSON.stringify(posts, null, 2);
  const blob = new Blob([jsonStr], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "blog_studio_backup.json";
  a.click();
  URL.revokeObjectURL(url);
  showToast("Backup JSON exported successfully!");
}

// Import database from JSON file
function importJSONBackup(e) {
  const file = e.target.files[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = function(event) {
    try {
      const importedData = JSON.parse(event.target.result);
      if (!Array.isArray(importedData)) {
        throw new Error("Invalid backup file: Root must be a JSON array.");
      }
      
      // Basic validation of import schema
      const isValid = importedData.every(item => 
        item.title && item.slug && item.content && Array.isArray(item.tags)
      );

      if (!isValid) {
        throw new Error("Invalid schema structure. Make sure import contains title, slug, content and tags.");
      }

      if (confirm(`Do you want to overwrite your existing ${posts.length} posts with ${importedData.length} imported posts?`)) {
        posts = importedData;
        saveToLocalStorage();
        currentPostId = null;
        resetEditor();
        renderPostsList();
        showToast("Backup restored successfully!");
      }
    } catch(err) {
      alert(`Import failed: ${err.message}`);
    }
    // Reset file input value so same file can be imported again
    importJsonFile.value = "";
  };
  reader.readAsText(file);
}
